
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  db:
    image: postgres:alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
  thumbnailer:
    depends_on:
      - rabbitmq
      - db
    image: file-explorer-thumbnailer:dev
    container_name: thumbnailer
    volumes:
      - ../:/usr/app/
    ports:
      - "8441:8441"
    environment:
      ENVIRONMENT: "development"
      PORT: "8441"
      LOG_LEVEL: "debug"
      RABBITMQ_HOST: "rabbitmq"
      PG_DATABASE: "postgres"
      PG_USERNAME: "postgres"
      PG_PASSWORD: "password"
      PG_HOST: "db"
      PG_PORT: "5432"
      AWS_REGION: "${AWS_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  backend:
    image: lichfiet/file-explorer-backend:latest
    container_name: backend
    ports:
      - "8443:8443"
    environment:
      APP_NAME: "file-explorer-backend"
      PORT: "8443"
      LOG_LEVEL: "info"
      RABBITMQ_HOST: "rabbitmq"
      AWS_REGION: "${AWS_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"